### ISSUE TITLE
Add support for custom normalization grammemes

### ISSUE THREAD

**Issue by dveselov** [natasha/yargy#19]
This ability required for some entities, like `Соединенные Штаты Америки`, that must be normalized as plural (and now its normalized form is `Соединить Штат Америки`)

This, also, can be done via passing custom normalization method:

```python
from yargy.normalization import get_inflected_text

def my_normalization_method(tokens):
    return get_inflected_text(tokens, {'plur', 'nomn'})

{
    'labels': [ ... ],
    'normalization': my_normalization_method,
}
```

**Comment by kuk** [comment]
Такое имеет смысл делать не средствами yargy, запускать отдельно морфологический тегер, приводить словарь к нормальной форме перед запуском yargy, см. https://nbviewer.jupyter.org/github/natasha/natasha/blob/master/docs.ipynb#Phrase-normalization
