### ISSUE TITLE
Remove INT-RANGE, INT-SEPARATED, FLOAT, FLOAT-RANGE, EMAIL, PHONE tokenizer rules

### ISSUE THREAD

**Issue by alexanderkuk** [natasha/yargy#20]
Например, нужно распарсить дату 3.12.2008 . Ожидается, что она будет разбита на 5 частей: 3, '.', 12, '.', 2008. Из-за FLOAT она будет разбита на 3 части: 3.12, '.', 2008. Это неожиданно, с такими токенами неудобно работать.

Для INT-RANGE, INT-SEPARATED, FLOAT-RANGE, EMAIL, PHONE у меня нет подобных примеров, но я уверен они существуют.

Предлагаю убрать эти правила из токенизатора.

**Comment by dveselov** [comment]
Привет. А что делать с правилами, которым нужны эти типы токенов?
Например, `1,5 миллиона рублей` или `18-20 июня` или `10 000 000 рублей`.

**Comment by alexanderkuk** [comment]
Писать более сложные грамматики. Например`
```
FLOAT -> NUMBER ',' NUMBER
MONEY -> FLOAT 'миллиона' 'рублей'

DATE_RANGE -> DAY '-' DAY MONTH
```

**Comment by dveselov** [comment]
Да, логично. `EMAIL` и `PHONE`, наверное, стоит оставить т.к. они не будут мешать (слишком специфичные данные же)

**Comment by alexanderkuk** [comment]
>Да, логично. EMAIL и PHONE, наверное, стоит оставить т.к. они не будут мешать (слишком специфичные данные же)

> Мне кажется, правильнее будет добавить разбор урлов как отдельных токенов - т.е. так же как EMAIL или PHONE.

Теоретически да, но на практике это стрёмно по двум причинам:
1. Может обработаться не всё. Текст может быть с кривыми урлами. Из практики: "на странице пользователя http://vk.com id938112". Не уровне токенайзера ты никогда не учтёшь все возможные варианты.
2. Может обработаться лишнее. Это гораздо неприятнее, чем п.1. Вспомним про FLOAT и даты вида 12.01.2015. У меня пока нет примеров для PHONE, EMAIL и URL, но я уверен, что они есть. Кажется, что регулярка для PHONE будет метчить только телефоны. 100% есть страницы с реквизитами компаний, где ИНН, ОГРН или ОКПО пометчится как телефон. Чтобы извлечь реквизиты придётся писать что-то типа eq("ОКПО"), eq(":"), gram("PHONE") gram(INT), это криво.

**Comment by alexanderkuk** [comment]
Вот пример где PHONE сработал зря 
```
http://vk.com/video 183227813 165484372

[Token('http', (0, 4), [{'grammemes': {'LATN'}, 'normal_form': 'http'}]),
 Token(':', (4, 5), [{'grammemes': {'PUNCT'}, 'normal_form': ':'}]),
 Token('/', (5, 6), [{'grammemes': {'PUNCT'}, 'normal_form': '/'}]),
 Token('/', (6, 7), [{'grammemes': {'PUNCT'}, 'normal_form': '/'}]),
 Token('vk', (7, 9), [{'grammemes': {'LATN'}, 'normal_form': 'vk'}]),
 Token('.', (9, 10), [{'grammemes': {'PUNCT'}, 'normal_form': '.'}]),
 Token('com', (10, 13), [{'grammemes': {'LATN'}, 'normal_form': 'com'}]),
 Token('/', (13, 14), [{'grammemes': {'PUNCT'}, 'normal_form': '/'}]),
 Token('video', (14, 19), [{'grammemes': {'LATN'}, 'normal_form': 'video'}]),
 Token('183227813 16548', (19, 35), [{'grammemes': {'PHONE'}, 'normal_form': '183227813 16548'}]),
 Token(4372, (35, 39), [{'grammemes': {'NUMBER', 'INT'}, 'normal_form': '4372'}])]
```
