### ISSUE TITLE
Do not decode roman numbers

### ISSUE THREAD

**Issue by alexanderkuk** [natasha/yargy#24]
Есть урл http://vilayatiu.co.cc . Ожидается что он разобьётся на токены http : / / vilayatiu . co . cc. Но он разбивается на http : / / vilayatiu . co . 0. 

сс принимается за римскую цифру. cc декодируется в 0, потому что decode_roman_number предполагает, что число будет записано большими буквами.

Предлагаю не декодировать римские цифры. И не убирать LATN с них

**Comment by dveselov** [comment]
Мне кажется, правильнее будет добавить разбор урлов как отдельных токенов - т.е. так же как `EMAIL` или `PHONE`.

**Comment by dveselov** [comment]
Потому, что сейчас римские цифры используются в правилах для дат и событий (`XX век`, `XXI международный экономический форум`)

**Comment by alexanderkuk** [comment]
Легко себе представить псевдо римские цифры не в урлах: "Re: [CC] В эмейле", "Размеры L, XS, XL"

> Потому, что сейчас римские цифры используются в правилах для дат и событий (XX век, XXI международный экономический форум)

Их можно поддержать и без римских цифр в токенайзере

**Comment by dveselov** [comment]
Вынесем в отдельный лейбл.

**Comment by dveselov** [comment]
Неактуально.
