### ISSUE TITLE
[RFC] Interface to add rules to tokenizer

### ISSUE THREAD

**Issue by alexanderkuk** [natasha/yargy#25]
Предлагаю инициализировать токенайзер списком правил. По умолчанию список будет состоять из RUSSIAN, LATN, QUOTE, INT, PUNCT, END-OF-LINE. Но реализация для EMAIL, PHONE, URL тоже будет и пользователь по желанию сможет их добавить. Нужно явно указать, что Наташа будет работать только со стандартным списком правил.

Правила могут быть оформлены так:
```
class IntRule(TokenRule):
    pattern = r'[+-]?\d+'
    construct = int
    grammemes = {'NUMBER', 'INT'}

class EmailRule(TokenRule):
    pattern = r'[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+'
    grammemes = {'EMAIL'}
```

Правила добавляются так:
```
tokenizer = Tokenizer()
tokenizer.add_rules(
    EmailRule(),
    PhoneRule()
)
parser = Parser(G, tokenizer=tokenizer)
```

Продвинутый пользователь сможет создать и добавить какое-нибудь необычное правило, которое не вписывается в пайплайн

**Comment by dveselov** [comment]
Привет. Отличная идея.

Сейчас, кстати, можно сделать (примерно) так же - т.е. можно передавать параметр `pattern` в токенизатор и определять в нем методы для конвертации строк в токены.

Но отдельные объекты для правил, конечно, выглядят лучше.

**Comment by dveselov** [comment]
Ещё (касательно токенизатора) нужно будет сделать одновременный разбор несколькими правилами (это больше относится к #24, наверное).
Т.е. список словоформ `XII` будет таким: `[ ('latin', '...'), ('int', 'romn', '...) ]`

**Comment by alexanderkuk** [comment]
В https://github.com/natasha/yargy/pull/48 в токенизатор добавлен метод `add_rules`
