### ISSUE TITLE
Cython compilation

### ISSUE THREAD

**Issue by Angriff** [natasha/yargy#39]
[setup.zip](https://github.com/natasha/yargy/files/1310189/setup.zip)
Добрый день! Для ускорения работы попробовал собрать вашу библиотеку с помощью cython. Если интересно, то прикрепляю setup.py файл, который использовал для этого.

Собрать не получилось без 2-х небольших правок (возможно это небольшие баги, которые стоит поправить):
1. В файле interpretation/fact.py отсутствует импорт `assert_type` из yargy.utils. И это очень похоже на баг =)
1. В файле rule/constructors.py сборка падала на строчке 196:
```self.rule = rule(item, *items)```. Тут я не уверен, что это баг, но замена `rule` на `Rule` помогла и сборка успешно прошла.

Однако, при попытке использовать полученную собранную либу вылетает ошибка:
> C:\Users\alexandr.romanenko\workspace\cython\yargy\parser.pyx in yargy.parser.Parser.__init__ (yargy\parser.c:6233)()
> 
> C:\Users\alexandr.romanenko\workspace\cython\yargy\rule\constructors.pyx in yargy.rule.constructors.Rule.normalized (yargy/rule\constructors.c:3524)()
> 
> C:\Users\alexandr.romanenko\workspace\cython\yargy\rule\constructors.pyx in yargy.rule.constructors.Rule.transform (yargy/rule\constructors.c:3311)()
> 
> C:\Users\alexandr.romanenko\workspace\cython\yargy\visitor.pyx in yargy.visitor.TransformatorsComposition.__call__ (yargy\visitor.c:1910)()
> 
> C:\Users\alexandr.romanenko\workspace\cython\yargy\rule\transformators.pyx in yargy.rule.transformators.RuleTransformator.__call__ (yargy/rule\transformators.c:1531)()
> 
> C:\Users\alexandr.romanenko\workspace\cython\yargy\rule\constructors.pyx in genexpr (yargy/rule\constructors.c:4227)()
> 
> ValueError: generator already executing

Ошибка возникает при попытке создать экземпляр класса Parser. При этом если пользоваться обычной python версией библиотеки, все работает и создается корректно

Понимаю, что вопрос довольно абстрактный, но возможно вы подскажите, что я сделал не так?
Возможно, правка 2 была не верна, и чтобы собрать yargy под cython нужны другие (возможно, более глобальные) исправления кода. Или может быть по этому небольшому сообщению об ошибке Вы все-таки поймете, в чем проблема... 
Все-таки получить 30% ускорения работы библиотеки просто за счет сборки cython - это очень заманчиво =) 

И еще вопрос: на данный момент `pip install yargy` устанавливает версию 0.8.0 библиотеки. Я правильно понимаю, что нужно устанавливать библиотеку прямо из github, забирая последнюю версию (0.9.1), потому как все примеры и туториалы на 0.8.0 не работают...

**Comment by alexanderkuk** [comment]
Я бы посоветовал вам попробовать использовать Pypy. На моим задачах ускорение бывает до 10x.

Да, пока надо ставить из github

**Comment by Angriff** [comment]
Спасибо за совет. Подумаю в эту сторону...

А правки, о которых я написал, правильные?

**Comment by alexanderkuk** [comment]
Первая, да. А вторая не совсем. В функции rule не просто вызывается Rule, там ещё обрабатываются аргументы:
```
def rule(*items):
    production = Production([prepare_production_item(_) for _ in items])
    return Rule([production])
```
