### ISSUE TITLE
Фиксировать версии pymorphy2 и pymorphy2_dicts_ru при тестировании

### ISSUE THREAD

**Issue by kuk** [natasha/yargy#40]
В версии словарей 2.4.404381.4454046, которая у меня и на https://b-labs.pro/natasha/, у 'куценко', tag=OpencorporaTag('NOUN,anim,ms-f,Fixd,Surn plur,loct') в версии 2.4.393658.3725883, которая сейчас в Travis tag=OpencorporaTag('NOUN,anim,GNdr,Ms-f,Fixd,Surn sing,nomn').

У меня ms-f, там Ms-f. У меня тест c Гоша Куценко ломается, там работает.

**Comment by dveselov** [comment]
Да, есть такое: https://github.com/OpenCorpora/opencorpora/issues/795
