### ISSUE TITLE
Не давать пользователю лёгкий доступ к граммемам pymorphy

### ISSUE THREAD

**Issue by alexanderkuk** [natasha/yargy#41]
Предлагается добавить слой абстракции над граммемами pymorphy 
1. Не прикольно писать gram('Ms-f'). Можно опечататься.
2. Похоже, названия граммем могут меняться, см. https://github.com/natasha/yargy/issues/40

**Comment by dveselov** [comment]
Хотелось бы увидеть как это будет выглядеть

**Comment by alexanderkuk** [comment]
В https://github.com/natasha/yargy/pull/48 дано решение. Просто проверять, что написано в `gram`. Например, правила с `gram('foobar')` не запустятся
