### ISSUE TITLE
Как правильно выкусывать имена объектов?

### ISSUE THREAD

**Issue by arturgspb** [natasha/yargy#45]
Привет! Например у меня такие строки:

"Скиньте документы по клиенту Рога и Копыта за август"
или
"Скиньте документы по клиенту Рик за август"
или 
"Скиньте акты по клиенту Horns and hooves за август"

С учетом того, что "клиенту" у меня разбирается в ENTITY_G = gram('Entity')
, а "август" разбирается в DATE_G 
```
DATE_G = or_(
    rule(
        DAY.interpretation(Date.day),
        MONTH_NAME.interpretation(Date.month.inflected()),
        YEAR.interpretation(Date.year)
    ),
   ....
).interpretation(
    Date
).named('DATE')
```

Т.е. имена клиентов могут быть и на русском и на английском и на латышском и могут не обрамляться кавычками.
На крайний случай я могу из БД выбрать все вариации имен клиентов и попробовать пихнуть в Газеттир или типа того, чтобы объединить слова, но желательно бы этого не делать таким образом.

Как лучше сделать?

**Comment by arturgspb** [comment]
@alexanderkuk поможете?

**Comment by alexanderkuk** [comment]
Какого-то магического решения тут нет.
1. Да, если есть все названия, можно сделать из них словарь
2. Внимательно посмотреть на возможные названия, выделить закономерности. Например
```
from yargy.predicates import gram, is_capitalized

CAPITAL = is_capitalized()
QUOTE  = gram('QUOTE')

RULE = or_(
    rule(CAPITAL),
    rule(CAPITAL, 'и', CAPITAL),
    rule(
        QUOTE,
        not_(QUOTE).repeatable(),
        QUOTE   
    )
)
```
3. Натренировать CRF-классификатор, но это сложно.

**Comment by arturgspb** [comment]
Пасиб!
