### ISSUE TITLE
Lock() в Parser

### ISSUE THREAD

**Issue by alexanderkuk** [natasha/yargy#49]
C самой первой версии yargy в парсере создаётся и используется Lock https://github.com/natasha/yargy/blob/master/yargy/parser.py#L187 . @dveselov , это точно нужно? Я просто не очень шарю в этой теме. В своей практике вроде бы эта фича мне не пригождалась. Может убрать? Если надо, пользователь может сам создать Lock() при использовании парсера

**Comment by dveselov** [comment]
Привет, это делает парсер thread-safe, т.е. делает его работу корректной при использовании из нескольких потоков. Можно убрать лок и добавить предупреждение, как сделано в pymorphy2.

**Comment by alexanderkuk** [comment]
Может просто в доке написать, что типа парсер не thread-safe? ))

**Comment by dveselov** [comment]
Да, я про это и говорю)

**Comment by dveselov** [comment]
Убрали в https://github.com/natasha/yargy/commit/1334e6dea94ac21ecfdf8001d446e93a76b87e6d
