### ISSUE TITLE
Multiinterpretation of all facts attributes

### ISSUE THREAD

**Issue by julstarkova** [natasha/yargy#53]
Возможно ли распарсить одно слово проинтерпретировав его фактом с несколькими активными полями?
**Пример:** хочется находить различные породы собак, а на выходе получать документ,откуда можно будет собирать какую-то статистику.

```
Breed = fact('Breed',
    ['weight','hight','origin','life span'])
```
Пока, я так понимаю, есть вариант писать парсер для каждой такой породы, например
```
BreedCorgi = fact('Breed',
    [attribute('weight', 15.5), attribute('hight', 29.5), attribute(' origin', 'Wales'), attribute('life span', 12)])
CORGI = rule(caseless('корги')).interpretation(BreedCorgi)
```
Но что делать когда словарь таких пород растет, есть ли какой-то более гуманный способ?
Функция интерпретации, насколько можно судить из справочника, не позволяет одно слово интерпретировать по-разному -- получается, что , если встречается слово "корги", то  путем интерпретации и присвоению констаты можно обновить только один атрибут.(т.к. любая новая интерпретацию будет перезаписывать старую)

**Comment by julstarkova** [comment]
@alexanderkuk , не подскажете?

**Comment by alexanderkuk** [comment]
Не понял вопрос. Может быть, если вы покажете примеры текстов, которые хотите разбирать, станет понятнее.

**Comment by julstarkova** [comment]
Выбор самого текста не принципиален, можно взять дамп вики, например, и выбрать статьи об известных писателях и составить какую-нибудь статистику. Чтобы было понятнее ,вот выдержка из рандомной статьи рунета, где присутсвуют названия различных пород собак.

> Если человек отличается высокой степенью активности и считается приверженцем подвижного здорового образа жизни — любит велосипед, занимается бегом, катается на роликах, подойдет активный, подвижный и шустрый представитель породы собачьих. К примеру, ирландский сеттер, хаски, грейхаунд левретка.
Спокойный и уравновешенный будущий владелец пусть присмотрится повнимательнее к ретриверам или мопсам. Деловым активным людям с волевым характером возможно приобрести немецкую овчарку, добермана или ротвейлера.

Хотелось бы выделить все сущности-породы, и поставить им в соответствие определенные характеристики, как показано выше.
В идеале хотелось бы написать **один парсер для всех пород**, а не для каждой породы свой. Вопрос состоит в том, возможно ли это сделать средствами библиотеки?

**Comment by alexanderkuk** [comment]
Из этого текста с помощью ярги-парсера можно извлекать подстроки типа "ирландский сеттер", "хаски", "грейхаунд левретка". Для характеристик можно завести отдельную таблицу вне парсера:

```
{
  "хаски": {
    'weight': 15.5,
     ...
  },
  "грейхаунд левретка": {
    ...
   }
}

```

**Comment by julstarkova** [comment]
Спасибо, это понятно. Вопрос состоит в том, можно ли обрабатывая одну единицу текста проинтерпретировать ее не просто как один атрибут(например тот же вес), а как какое-то подмножество атрибутов(происхождение, вес и окрас). У меня уже чисто исследовательский интерес, понятно, что выше изложенную задачу будет проще сделать не с yargy, но любопытно посмотреть на возможности библиотеки.

**Comment by alexanderkuk** [comment]
> можно ли обрабатывая одну единицу текста проинтерпретировать ее не просто как один атрибут(например тот же вес), а как какое-то подмножество атрибутов
Нет, нельзя

> но любопытно посмотреть на возможности библиотеки
Возможности можно примерно понять из репозитория с примерами http://nbviewer.jupyter.org/github/natasha/yargy-examples/tree/master/

**Comment by julstarkova** [comment]
Спасибо за ответ,удачи)
