### ISSUE TITLE
Can we use Yargy for other language?

### ISSUE THREAD

**Issue by pilgrim2go** [natasha/yargy#54]
Hi,

Can we use Yargy for other language?

If yes, can you guys give an example?

( Sorry I'm still a newbie here)

**Comment by alexanderkuk** [comment]
Hi, currently yargy is for russian for python . One can use yargy with any language but without morphology (normal("cat") will not match "cats"). For example see http://nbviewer.jupyter.org/github/natasha/yargy-examples/blob/master/02_console/notes.ipynb , it is not pure english but gives some idea
