### ISSUE TITLE
Короткое название вместо interpretation

### ISSUE THREAD

**Issue by xamgore** [natasha/yargy#56]
Привет. Часто приходится интерпретировать деревья, и постоянно писать слово `interpretation`. Оно сложное (erpre), сильно раздувает грамматику, с точки зрения чтения кода становится трудно ориентироваться.

Может, попробуем добавить альяс для него? Например, `means`:

```python
VESTIBULE = rule(or_(
    rule(
        ...
    ).means(Fact.one),
    rule(
        ...
    ).means(Fact.two),
).means(Fact)
```

Кажется, это ничего не ломает, но сильно упрощает жизнь.

**Comment by alexanderkuk** [comment]
Ой, в yargy есть ряд названий, которые можно переосмыслить и назвать по-другому, например, morph_pipeline, dictionary, normalized, type. Соглашусь, means выглядит поприкольнее interpretation. Но
1. Обратная совместимость. Можно поддержать две записи, но это неудобно читать, разный код будет означать одно и то же.
2. Так принято называть. В Томите тоже есть "интерпретация" и слово "interp"

Короче, предлагаю вам привыкнуть )) Как человек, который написал уже кучу грамматик для yargy, могу сказать, что на практике длинное слово interpretation +- последнее, что будет вас беспокоить ))) Если ооочень хочется, как-нибудь запатчить название метода в рантайме.
