### ISSUE TITLE
Вывод списков с фактами

### ISSUE THREAD

**Issue by xamgore** [natasha/yargy#58]
Если выводить факты, внутри которых есть списки фактов, то получается вот такой не очень красивый вывод:

![image](https://user-images.githubusercontent.com/4586392/49771704-771a4000-fcfb-11e8-8f71-918a74efd573.png)

Последовательный вывод (выше) подходит для списка чисел или строк, например. Но здесь хочется, чтобы `Station(...)` всё время начинались с новой строки с отступом:

```
StationAndTransfer(station=Station(name='Спасская',
                                   num=[]),
                   transfer=[Station(name='Садовая',
                                     num=[]),
                     ——————> Station(name='Сенная площадь',
                                     num=[])])
```

Если нет возможности или желания такое делать, я могу попробовать сделать пул реквест, правда, будет хорошо, если подскажете, в какие файлы смотреть.

**Comment by kuk** [comment]
Нет возможности. Можно определить формат вывода для своих классов для list нельзя.
