### ISSUE TITLE
Additional labels for quote matching

### ISSUE THREAD

**Issue by dveselov** [natasha/yargy#6]
Currently, `yargy` doesn't understands that text can be wrapped in different types of quotes, like 'classic': `" and '` and a lot of different typographic quotes: `« » / „ “ / “ ” / ‘ ’ / „ ” / and so on`

There should be special label(s?), that checks some quote-related stuff:
1. Type: opening, closing or generic quote
2. Same type as opening quote (for matching closing quotes)
3. Same group as opening quote (because without that, `« (opening)` and `“ (closing)` quotes, will be matched together)

**Comment by dveselov** [comment]
OK, added some description.

**Comment by kuk** [comment]
Предлагается работать с текстом кавычках через генерацию правил, см. https://nbviewer.jupyter.org/github/natasha/yargy/blob/master/docs/cookbook.ipynb#%D0%93%D0%B5%D0%BD%D0%B5%D1%80%D0%B0%D1%86%D0%B8%D1%8F-%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D0%BB
