### ISSUE TITLE
Нормализация отдает предпочтение мужским именам

### ISSUE THREAD

**Issue by strawberrypie** [natasha/yargy#60]
При нормализации токена она [происходит](https://github.com/natasha/yargy/blob/53462891810c73fa9098c62f8840b0952425077e/yargy/token.py#L46
) крайне просто — выбирается самый первый вариант из предложенных.
Такое поведение иногда ошибочно распознает имена, например: `"Актриса Ярослава Новожилова"` — извлекается `{'first': 'ярослав', 'last': 'новожилов'}`.

Нужно как-то иначе проводить нормализацию, так чтобы был учет контекста. Скорее всего это потребует более серьезных методов обработки предложения, например составления дерева зависимостей между словами в нем. Либо же это проблема встроенного в PyMorphy CRF-теггера.

**Comment by alexanderkuk** [comment]
Попробуйте использовать согласование, в документации есть пример с ФИО https://yargy.readthedocs.io/ru/latest/#id9

**Comment by strawberrypie** [comment]
Согласование с "актриса" перед именем? Это я для примера привел, хотелось бы чтобы распознавалось корректно при произвольном контексте.

**Comment by alexanderkuk** [comment]
Да, с "актриса".

**Comment by kuk** [comment]
Также имеет смысл делать нормализацию не средствами yargy, запускать отдельно морфологический тегер, приводить словарь к нормальной форме перед запуском yargy, см. https://nbviewer.jupyter.org/github/natasha/natasha/blob/master/docs.ipynb#Phrase-normalization
