### ISSUE TITLE
TypeError: mixed types: 

### ISSUE THREAD

**Issue by vitalij23** [natasha/yargy#63]
TypeError: mixed types: [<class 'yargy.rule.constructors.Rule'>, <class 'yargy.rule.constructors.Rule'>]

```
nds_rule = rule(
    and_(and_(rule(bez_x_nds, not_(nds)), rule(not_(nds), bez_nds_x)),
        or_(rule(
            bez_x_nds, nds
            ),
            rule(
                nds, bez_nds_x
            ),
            rule(
                not_nds            
            )
        )
    )
)
```

**Comment by kuk** [comment]
Да, ошибка странная. А что значит `and_(rule(bez_x_nds, not_(nds)), rule(not_(nds), bez_nds_x))`? В yargy же нельзя `and(rule(...), rule(...))` и вообще непонятно что это значит по смыслу

**Comment by kuk** [comment]
Пояснение к ошибке про mixed types есть в документации https://nbviewer.jupyter.org/github/natasha/yargy/blob/master/docs/cookbook.ipynb#TypeError:-mixed-types
