### ISSUE TITLE
Как задать rule с ограничением все кроме... 

### ISSUE THREAD

**Issue by edgar2597** [natasha/yargy#68]
Как задать rule с ограничением все кроме... То есть если в тексте есть  дата "06.12.2018" и время "07.20" и нужно извлекать время , как можно в rule для парсера настроить ограничение что наличие последующей точки после минуты означало бы что вариант не подходит? Я не нашел подобного в справочнике

**Comment by kuk** [comment]
Написать 2 правила: для даты и для времени. Извлекать обе сущности, для "06.12.2018" сработает правило для даты потому что у него выше покрытие (метч длиннее). Дальше метчи для даты игнорировать

**Comment by edgar2597** [comment]
ок, но разве можно извлекать две сущности одновременно? то есть я создал два отдельных правила для времени и для даты,  но как их можно применить одновременно?

**Comment by edgar2597** [comment]
ок, но разве можно извлекать две сущности одновременно? то есть я создал два отдельных правила для времени и для даты,  но как их можно применить одновременно?

**Comment by edgar2597** [comment]
ок, но разве можно извлекать две сущности одновременно? то есть я создал два отдельных правила для времени и для даты, но как их можно применить одновременно для одного парсера?

**Comment by kuk** [comment]
```
A = rule(...)
B = rule(...)
С = or_(A, B)
parser = Parser(C)
parser.findall(...)
```

**Comment by edgar2597** [comment]
повявляется это ValueError: no .interpretation(...) for root rule

**Comment by edgar2597** [comment]
сделал. при
for match in parser.findall(text):
    print(match.fact)
выдает ValueError: no .interpretation(...) for root rule

**Comment by edgar2597** [comment]
но с таким парсером нельзя извлекать факты for match in parser.findall(text):
    print(match.fact). Выдается ValueError: no .interpretation(...) for root rule

**Comment by kuk** [comment]
```
AFact = fact(...)
BFact = fact(...)
CFact = fact('C', ['value'])

A = rule(...).interpretation(AFact).interpretation(CFact.value)
B = rule(...).interpretation(BFact).interpretation(CFact.value)
С = or_(A, B).interpretation(CFact)

parser = Parser(C)
for match in parser.findall(...):
    print(match.fact.value)
```
