### ISSUE TITLE
использовать normalized с большим количеством слов

### ISSUE THREAD

**Issue by edgar2597** [natasha/yargy#70]
Подскажите пожалуйста, как можно использовать normalized с большим количеством слов из списка? В справочнике я увидел лишь пример когда нужно прописывать каждый случай(POSITION = or_(
    rule(normalized('генеральный'), normalized('директор')),
    rule(normalized('бухгалтер'))
)), но если слов несколько десятков или сотен, как можно записать это короче?

**Comment by kuk** [comment]
См. morph_pipeline в https://yargy.readthedocs.io/ru/latest/#id3

**Comment by edgar2597** [comment]
спасибо
